name = "jobs-news-portal"
main = "src/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "jobs-news-db"
database_id = "2995e03a-c92b-45d4-820b-42e4bac11113"

[assets]
directory = "./public"
binding = "ASSETS"

[observability]
enabled = true
